use std::net::Ipv4Addr;

use anyhow::Result;
use colored::Colorize;
use serde::{Deserialize, Serialize};
use crate::format;

/// DNS 预设
pub const DNS_PRESETS: &[(&str, &[&str])] = &[
    ("alibaba", &["223.5.5.5", "223.6.6.6"]),
    ("ali", &["223.5.5.5", "223.6.6.6"]),
    ("114", &["114.114.114.114", "114.114.115.115"]),
    ("tencent", &["119.29.29.29", "119.28.28.28"]),
    ("dnspod", &["119.29.29.29", "119.28.28.28"]),
    ("baidu", &["180.76.76.76"]),
    ("google", &["8.8.8.8", "8.8.4.4"]),
    ("cloudflare", &["1.1.1.1", "1.0.0.1"]),
    ("opendns", &["208.67.222.222", "208.67.220.220"]),
];

/// 国内 DNS 预设名（用于分类判断）
const DOMESTIC_DNS_NAMES: &[&str] = &["alibaba", "ali", "114", "tencent", "dnspod", "baidu"];
/// 海外 DNS 预设名
const FOREIGN_DNS_NAMES: &[&str] = &["google", "cloudflare", "opendns"];

/// 判断两个 IPv4 地址是否在同一 /24 子网
fn ip_in_subnet_24(ip: &str, server: &str) -> bool {
    let (Ok(ip_addr), Ok(server_addr)) = (ip.parse::<Ipv4Addr>(), server.parse::<Ipv4Addr>()) else {
        return false;
    };
    let ip_octets = ip_addr.octets();
    let server_octets = server_addr.octets();
    ip_octets[0] == server_octets[0]
        && ip_octets[1] == server_octets[1]
        && ip_octets[2] == server_octets[2]
}

/// 判断 IP 是否属于已知国内 DNS 服务器
pub fn is_domestic_dns(ip: &str) -> bool {
    DOMESTIC_DNS_NAMES.iter().any(|name| {
        DNS_PRESETS.iter()
            .find(|(n, _)| n == name)
            .is_some_and(|(_, servers)| servers.iter().any(|s| ip_in_subnet_24(ip, s)))
    })
}

/// 判断 IP 是否属于已知海外 DNS 服务器
pub fn is_foreign_dns(ip: &str) -> bool {
    FOREIGN_DNS_NAMES.iter().any(|name| {
        DNS_PRESETS.iter()
            .find(|(n, _)| n == name)
            .is_some_and(|(_, servers)| servers.iter().any(|s| ip_in_subnet_24(ip, s)))
    })
}

/// DNS 配置
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DnsConfig {
    pub servers: Vec<String>,
}

/// 显示当前 DNS 配置
pub fn show_dns() -> Result<()> {
    println!("{}", "🌐 DNS 配置".cyan().bold());
    println!();

    // 读取 /etc/resolv.conf
    let content = std::fs::read_to_string("/etc/resolv.conf")
        .unwrap_or_else(|_| "(无法读取 /etc/resolv.conf)".to_string());

    let mut found = false;
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("nameserver") {
            let server = trimmed.split_whitespace().nth(1).unwrap_or("");
            println!("  {} {}", "•".bold(), server.cyan());
            found = true;
        }
    }

    if !found {
        println!("  (未找到 DNS 配置)");
    }

    Ok(())
}

/// 列出所有 DNS 预设
pub fn list_dns_presets() -> Result<()> {
    println!("{}", "🌐 DNS 预设".cyan().bold());
    println!();

    let mut table = format::new_table(&["预设", "DNS 服务器"]);
    for (name, servers) in DNS_PRESETS {
        table.add_row(vec![name.cyan().to_string(), servers.join(", ")]);
    }
    println!("{table}");

    println!();
    println!("使用 {} 设置 DNS", "nz-switch dns set <preset>".cyan());

    Ok(())
}

/// 设置 DNS (写入 profile 配置 + 打印手动执行提示)
pub fn set_dns(source: &str) -> Result<()> {
    // 解析预设
    let servers: Vec<&str> = DNS_PRESETS.iter()
        .find(|(name, _)| *name == source)
        .map(|(_, servers)| servers.to_vec())
        .unwrap_or_else(|| {
            // 尝试作为 IP 地址解析
            if source.contains('.') {
                vec![source]
            } else {
                vec![]
            }
        });

    if servers.is_empty() {
        println!("{} 未知的 DNS 预设: {}", "❌".red(), source);
        println!("运行 {} 查看可用预设", "nz-switch dns list".cyan());
        return Ok(());
    }

    // 保存到当前 profile
    let dns_servers: Vec<String> = servers.iter().map(|s| s.to_string()).collect();
    crate::config::mutate_current_profile(|profile| {
        profile.dns = Some(DnsConfig {
            servers: dns_servers.clone(),
        });
    })?;
    println!("{} DNS 配置已保存到当前 profile", "✅".green());

    println!();
    println!("{} 实际修改系统 DNS 需要 sudo 权限，请手动执行:", "⚠".yellow());
    println!();

    // 构造 resolv.conf 内容
    let mut commands = String::new();
    commands.push_str("# 备份原始配置\n");
    commands.push_str("sudo cp /etc/resolv.conf /etc/resolv.conf.bak\n\n");
    commands.push_str("# 写入新配置\n");
    commands.push_str("sudo tee /etc/resolv.conf <<-'EOF'\n");
    commands.push_str("# Generated by nz-switch\n");
    for server in &servers {
        commands.push_str(&format!("nameserver {server}\n"));
    }
    commands.push_str("EOF\n");

    println!("{commands}");

    Ok(())
}

/// 应用 DNS 配置 (从 profile)，返回是否需要手动操作
pub fn apply_dns(dns: &Option<DnsConfig>) -> Result<Option<String>> {
    match dns {
        Some(dns_config) => {
            let mut instruction = String::from("sudo tee /etc/resolv.conf <<-'EOF'\n# Generated by nz-switch");
            for server in &dns_config.servers {
                instruction.push_str(&format!("\nnameserver {server}"));
            }
            instruction.push_str("\nEOF");

            println!("  {}", "DNS:".bold());
            println!("    {} 需要 sudo 权限，请手动执行:", "⚠".yellow());
            for line in instruction.lines() {
                println!("      {line}");
            }

            Ok(Some(instruction))
        }
        None => {
            println!("  {} DNS: 未配置", "ℹ".blue());
            Ok(None)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_dns_presets_not_empty() {
        assert!(!DNS_PRESETS.is_empty());
    }

    #[test]
    fn test_alibaba_preset_exists() {
        let alibaba = DNS_PRESETS.iter().find(|(name, _)| *name == "alibaba");
        assert!(alibaba.is_some());
        let (_, servers) = alibaba.unwrap();
        assert_eq!(servers[0], "223.5.5.5");
    }

    #[test]
    fn test_google_preset_exists() {
        let google = DNS_PRESETS.iter().find(|(name, _)| *name == "google");
        assert!(google.is_some());
        let (_, servers) = google.unwrap();
        assert_eq!(servers[0], "8.8.8.8");
    }

    #[test]
    fn test_all_presets_have_servers() {
        for (name, servers) in DNS_PRESETS {
            assert!(!servers.is_empty(), "DNS preset '{}' has no servers", name);
            for server in *servers {
                assert!(server.contains('.'), "DNS preset '{}' has invalid server '{}'", name, server);
            }
        }
    }
}
